export const relayRpcTags = {
  projectsList: "projects:list",
  projectsAddFolder: "projects:addFolder",
  projectsRemoveFromSidebar: "projects:removeFromSidebar",
  projectsRead: "projects:read",
  projectsGitMetadata: "projects:gitMetadata",
  projectsRevealInFinder: "projects:revealInFinder",
  projectsOpenInEditor: "projects:openInEditor",
  boardRead: "board:read",
  ticketIntakeDraft: "ticket:intakeDraft",
  ticketCreateDraft: "ticket:createDraft",
  ticketRedraft: "ticket:redraft",
  ticketGenerateSuggestions: "ticket:generateSuggestions",
  ticketCreateManual: "ticket:createManual",
  ticketCreateSubticket: "ticket:createSubticket",
  ticketLinkSubticket: "ticket:linkSubticket",
  ticketUnlinkSubticket: "ticket:unlinkSubticket",
  ticketStartAgentUpdate: "ticket:startAgentUpdate",
  ticketCancelAgentUpdate: "ticket:cancelAgentUpdate",
  ticketReferences: "ticket:references",
  ticketRead: "ticket:read",
  ticketSave: "ticket:save",
  ticketSaveAttachment: "ticket:saveAttachment",
  ticketMove: "ticket:move",
  ticketClarifications: "ticket:clarifications",
  ticketAnswerClarification: "ticket:answerClarification",
  ticketDelete: "ticket:delete",
  ticketDuplicate: "ticket:duplicate",
  ticketRevealFile: "ticket:revealFile",
  codexStatus: "codex:status",
  codexPreflightRun: "codex:preflightRun",
  codexStartRun: "codex:startRun",
  codexResumeRun: "codex:resumeRun",
  codexCancelRun: "codex:cancelRun",
  codexApproveAction: "codex:approveAction",
  codexSendRepositoryChatMessage: "codex:sendRepositoryChatMessage",
  codexReadRunEvents: "codex:readRunEvents",
  codexReadLatestRunSummary: "codex:readLatestRunSummary"
} as const;

export type RelayRpcTag = (typeof relayRpcTags)[keyof typeof relayRpcTags];
